version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./envs/prod.env
    ports:
      - "3001:3001"
